# Generated by Django 4.2.2 on 2026-02-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
