# Generated by Django 4.2.2 on 2026-02-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
        ('product', '0005_remove_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category'),
            preserve_default=False,
        ),
    ]
