# Generated by Django 4.2.2 on 2026-02-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
