# Generated by Django 4.2.2 on 2026-02-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
