# Generated by Django 4.2.2 on 2026-02-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_items',
        ),
    ]
